services:
  app:
    build:
      context: .
    container_name: ticket-sales-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:/app/dev.db
      - JWT_SECRET=supersecretkey
    volumes:
      - ./dev.db:/app/dev.db
    restart: always
